language: python

env:
    - CONDA="python=2.7 numpy"
    - CONDA="python=3.3 numpy"
    - CONDA="python=3.4 numpy"


before_install:
    - sudo apt-add-repository -y ppa:picaso/octave
    - sudo apt-get update -qq
    - sudo apt-get install -qq octave liboctave-dev
    - URL=http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
    - wget $URL -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes
    - conda update conda
    - conda info -a
    - travis_retry conda create -n test $CONDA numpy pip nose scipy
    - source activate test
    - travis_retry pip install coveralls
    - travis_retry pip install oct2py

install:
    - export PYTHONWARNINGS=all
    - python setup.py install

script:
    - if [[ $CONDA == python=2.7* ]]; then
        nosetests --verbose gsw;
      else
        nosetests --verbose --with-doctest --with-cov --cover-package gsw;
      fi

after_success:
    - coveralls
